### List Books with their current stocks
GET http://localhost:4004/admin/Orders


###
GET http://localhost:4004/drm/legalEntities/Customer

###
POST http://localhost:4004/drm/dataSubjectEndofBusiness
Content-Type: application/json

{
  "legalGround": "Order",
  "dataSubjectRole": "Customer",
  "dataSubjectID": "1003"
}

###
POST http://localhost:4004/drm/dataSubjectLegalEntities
Content-Type: application/json

{
  "legalGround": "Order",
  "dataSubjectRole": "Customer",
  "dataSubjectID": "1002"
}


###
POST http://localhost:4004/drm/dataSubjectRetentionStartDate
Content-Type: application/json

{
  "legalGround": "Order",
  "dataSubjectRole": "Customer",  
  "dataSubjectID": "1001",
  "legalEntity": "1001",
  "startTime": "paymentDate",
  "rulesConditionSet": [
    {
      "retentionID": "1"
    }
  ]
}

###
POST http://localhost:4004/drm/endofResidenceDataSubject
Content-Type: application/json

{
  "legalGround": "Order",
  "dataSubjectRole": "Customer",
  "startTime": "paymentDate",
  "legalEntitiesResidenceRules": [
    {
      "legalEntity": "1002",
      "residenceRules": [
        {
          "residenceDate": "2020-06-07T00:00:00",
           "conditionSet" :[]
        }
      ]
    },
    {
      "legalEntity": "1001",
      "residenceRules": [
        {
          "residenceDate": "2020-06-11T00:00:00",
           "conditionSet" :[]
        }
      ]
    }
  ]
}

###
POST http://localhost:4004/drm/dataSubjectInformation
Content-Type: application/json

{
  "applicationGroupName": "bookshop-drm-2",
  "dataSubjectRole": "Customer",
  "dataSubjectIds": [
    "1001","1002","1003"
  ]
}


###
POST http://localhost:4004/drm/deleteDSLegalGroundInstances
Content-Type: application/json

{
  "legalGround": "Order",
  "dataSubjectRole": "Customer",
  "dataSubjectID": "1002",
  "startTime": "paymentDate",
  "maxDeletionDate": "2016-10-10T23:59:59",
  "retentionRules": [
    {
      "legalEntity": "1002",
      "retentionPeriod": 5,
      "retentionUnit": "DAY",
      "conditionSet": []
    }
  ]
}


###
POST http://localhost:4004/drm/deleteDataSubject
Content-Type: application/json

{
  "applicationGroupName": "bookshop-drm-2",
  "dataSubjectRole": "Customer",
  "dataSubjectID": "1002",
  "maxDeletionDate": "2016-10-10T23:59:59"
}